"""Deterministic, rule-based advisor. Makes no API call; used for demos and tests."""

from __future__ import annotations

from ebay_comps.models import CompsStats, Condition, Listing, PricingRecommendation


def _charm(price: float) -> float:
    """Round to a .99 price point (e.g. 61.40 -> 60.99), never below 0.99."""
    return max(0.99, round(int(price) - 0.01, 2)) if price >= 1 else round(price, 2)


class MockAdvisor:
    name = "mock (rule-based, no LLM call)"

    def recommend(
        self, query: str, condition: Condition, stats: CompsStats, comps: list[Listing]
    ) -> PricingRecommendation:
        caveats = ["Generated by the offline mock advisor, not an LLM."]
        basis = stats.sold or stats.active
        if basis is None:
            return PricingRecommendation(
                recommended_price=0,
                quick_sale_price=0,
                price_range_low=0,
                price_range_high=0,
                confidence="low",
                reasoning="No usable comparable listings were found, so no price can be set.",
                caveats=caveats,
            )
        if stats.sold:
            label = f"{stats.sold.count} sold comps"
            confidence = "high" if stats.sold.count >= 15 else "medium"
        else:
            label = f"{basis.count} active listings (asking prices only)"
            confidence = "low"
            caveats.append("No sold data: active asking prices overstate what items sell for.")
        reasoning = (
            f"Anchored on the median of {label}: {basis.median:.2f} {stats.currency} "
            f"(IQR {basis.p25:.2f}-{basis.p75:.2f}). The quick-sale price sits at the 25th "
            f"percentile."
        )
        if stats.sell_through is not None:
            reasoning += f" Sell-through is {stats.sell_through:.0%}."
        return PricingRecommendation(
            recommended_price=_charm(basis.median),
            quick_sale_price=_charm(basis.p25),
            price_range_low=round(basis.p25, 2),
            price_range_high=round(basis.p75, 2),
            confidence=confidence,
            reasoning=reasoning,
            caveats=caveats,
        )
